"""create delivery events and occurrences

Revision ID: 09c2f3852c56
Revises: 843d3647db49
Create Date: 2026-07-08 14:19:54.002990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09c2f3852c56'
down_revision: Union[str, Sequence[str], None] = '843d3647db49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_events',
    sa.Column('delivery_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.Enum('DELIVERY_CREATED', 'DELIVERY_PLANNED', 'LOADING_STARTED', 'LOADING_FINISHED', 'DEPARTED_ORIGIN', 'IN_TRANSIT_UPDATE', 'STOP_STARTED', 'STOP_FINISHED', 'ARRIVED_CUSTOMER', 'UNLOADING_STARTED', 'UNLOADING_FINISHED', 'DELIVERY_COMPLETED', 'DELAY_REGISTERED', 'OCCURRENCE_REGISTERED', name='logistics_event_type'), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('responsible_area', sa.String(length=80), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], name=op.f('fk_delivery_events_delivery_id_deliveries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_delivery_events'))
    )
    op.create_index(op.f('ix_delivery_events_delivery_id'), 'delivery_events', ['delivery_id'], unique=False)
    op.create_index(op.f('ix_delivery_events_event_time'), 'delivery_events', ['event_time'], unique=False)
    op.create_index(op.f('ix_delivery_events_event_type'), 'delivery_events', ['event_type'], unique=False)
    op.create_table('occurrences',
    sa.Column('delivery_id', sa.Uuid(), nullable=False),
    sa.Column('occurrence_type', sa.Enum('TRAFFIC', 'WEATHER', 'MECHANICAL_FAILURE', 'CUSTOMER_QUEUE', 'ACCIDENT', 'DOCUMENT_ISSUE', 'ROUTE_DEVIATION', name='occurrence_type'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='occurrence_severity'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delay_minutes', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], name=op.f('fk_occurrences_delivery_id_deliveries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_occurrences'))
    )
    op.create_index(op.f('ix_occurrences_delivery_id'), 'occurrences', ['delivery_id'], unique=False)
    op.create_index(op.f('ix_occurrences_occurred_at'), 'occurrences', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_occurrences_occurrence_type'), 'occurrences', ['occurrence_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_occurrences_occurrence_type'), table_name='occurrences')
    op.drop_index(op.f('ix_occurrences_occurred_at'), table_name='occurrences')
    op.drop_index(op.f('ix_occurrences_delivery_id'), table_name='occurrences')
    op.drop_table('occurrences')
    op.drop_index(op.f('ix_delivery_events_event_type'), table_name='delivery_events')
    op.drop_index(op.f('ix_delivery_events_event_time'), table_name='delivery_events')
    op.drop_index(op.f('ix_delivery_events_delivery_id'), table_name='delivery_events')
    op.drop_table('delivery_events')
    # ### end Alembic commands ###
