"""create truck positions table

Revision ID: 18a6d9bc3324
Revises: e4a85146ff81
Create Date: 2026-07-08 15:49:11.437530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18a6d9bc3324'
down_revision: Union[str, Sequence[str], None] = 'e4a85146ff81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('truck_positions',
    sa.Column('truck_id', sa.Uuid(), nullable=False),
    sa.Column('delivery_id', sa.Uuid(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('speed_kmh', sa.Integer(), nullable=False),
    sa.Column('progress_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], name=op.f('fk_truck_positions_delivery_id_deliveries')),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], name=op.f('fk_truck_positions_truck_id_trucks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_truck_positions'))
    )
    op.create_index(op.f('ix_truck_positions_delivery_id'), 'truck_positions', ['delivery_id'], unique=False)
    op.create_index(op.f('ix_truck_positions_recorded_at'), 'truck_positions', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_truck_positions_truck_id'), 'truck_positions', ['truck_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_truck_positions_truck_id'), table_name='truck_positions')
    op.drop_index(op.f('ix_truck_positions_recorded_at'), table_name='truck_positions')
    op.drop_index(op.f('ix_truck_positions_delivery_id'), table_name='truck_positions')
    op.drop_table('truck_positions')
    # ### end Alembic commands ###
