"""create logistics core tables

Revision ID: 843d3647db49
Revises: b5594aac6471
Create Date: 2026-07-08 14:09:42.364702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '843d3647db49'
down_revision: Union[str, Sequence[str], None] = 'b5594aac6471'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('document', sa.String(length=20), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers')),
    sa.UniqueConstraint('document', name=op.f('uq_customers_document'))
    )
    op.create_table('drivers',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('license_number', sa.String(length=30), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'ON_TRIP', 'RESTING', 'INACTIVE', name='driver_status'), nullable=False),
    sa.Column('carrier_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], name=op.f('fk_drivers_carrier_id_carriers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drivers')),
    sa.UniqueConstraint('license_number', name=op.f('uq_drivers_license_number'))
    )
    op.create_table('trucks',
    sa.Column('plate', sa.String(length=10), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('capacity_tons', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('current_latitude', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('current_longitude', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('current_speed_kmh', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'LOADING', 'IN_TRANSIT', 'UNLOADING', 'MAINTENANCE', 'STOPPED', name='truck_status'), nullable=False),
    sa.Column('carrier_id', sa.Uuid(), nullable=False),
    sa.Column('driver_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], name=op.f('fk_trucks_carrier_id_carriers')),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_trucks_driver_id_drivers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trucks')),
    sa.UniqueConstraint('plate', name=op.f('uq_trucks_plate'))
    )
    op.create_table('deliveries',
    sa.Column('cte_number', sa.String(length=30), nullable=False),
    sa.Column('invoice_number', sa.String(length=30), nullable=False),
    sa.Column('origin_city', sa.String(length=80), nullable=False),
    sa.Column('origin_state', sa.String(length=2), nullable=False),
    sa.Column('weight_tons', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('freight_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('distance_km', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('planned_departure_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estimated_delivery_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_departure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_delivery_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'PLANNED', 'LOADING', 'IN_TRANSIT', 'DELIVERED', 'DELAYED', 'CANCELED', name='delivery_status'), nullable=False),
    sa.Column('carrier_id', sa.Uuid(), nullable=False),
    sa.Column('driver_id', sa.Uuid(), nullable=False),
    sa.Column('truck_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], name=op.f('fk_deliveries_carrier_id_carriers')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_deliveries_customer_id_customers')),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_deliveries_driver_id_drivers')),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], name=op.f('fk_deliveries_truck_id_trucks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deliveries')),
    sa.UniqueConstraint('cte_number', name=op.f('uq_deliveries_cte_number'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deliveries')
    op.drop_table('trucks')
    op.drop_table('drivers')
    op.drop_table('customers')
    # ### end Alembic commands ###
