"""refactor logistics domain

Revision ID: f0a6a060bd75
Revises: 09c2f3852c56
Create Date: 2026-07-08 14:41:03.907698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0a6a060bd75'
down_revision: Union[str, Sequence[str], None] = '09c2f3852c56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
    sa.Column('origin_city', sa.String(length=80), nullable=False),
    sa.Column('origin_state', sa.String(length=2), nullable=False),
    sa.Column('origin_latitude', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('origin_longitude', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('destination_city', sa.String(length=80), nullable=False),
    sa.Column('destination_state', sa.String(length=2), nullable=False),
    sa.Column('destination_latitude', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('destination_longitude', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('distance_km', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estimated_duration_hours', sa.Integer(), nullable=False),
    sa.Column('average_speed_kmh', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_routes'))
    )
    op.add_column('deliveries', sa.Column('route_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(op.f('fk_deliveries_route_id_routes'), 'deliveries', 'routes', ['route_id'], ['id'])
    op.add_column(
        "trucks",
        sa.Column(
            "odometer_km",
            sa.Numeric(precision=12, scale=2),
            nullable=False,
            server_default="0",
        ),
    )

    op.alter_column("trucks", "odometer_km", server_default=None)
    op.add_column('trucks', sa.Column('last_maintenance_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trucks', 'last_maintenance_at')
    op.drop_column('trucks', 'odometer_km')
    op.drop_constraint(op.f('fk_deliveries_route_id_routes'), 'deliveries', type_='foreignkey')
    op.drop_column('deliveries', 'route_id')
    op.drop_table('routes')
    # ### end Alembic commands ###
